### PR TITLE
fix(corl): update torch version expected by corl package

### LINKED ISSUE #37: Update Torch Version
CoRL 3.16.2 apparently wants to use a Torch 2.x.x version, but not 2.0.1. or 2.1.0.  sims currently requires Torch 1.13.0.  The Torch version should be updated to resolve this dependency conflict.  Part of the issue arises in that developing CoRL treats Torch as a required dependency, but not when a separate project is using CoRL.

I didn't see anything in the code base that directly utilized Torch.

### PR DESCRIPTION
**Pull request by jamie-cunningham**
Update the torch dependency to the version expected by the CoRL package for running CoRL experiments.

### CODE REVIEW

**Comment by jamie-cunningham** [comment]
For some reason `pytest-mock` was also not in the test dependency group. I'm not sure how that slipped through but I added it here.

**Review by keatincf — CHANGES_REQUESTED** [review]
I think the reason pytest-mock not being in the test dependencies wasn't caught was because the Github action that runs tests only runs the tests marked as unit_test.  The newer tests that use pytest-mock aren't marked as unit_test like the other unit tests.  We should either add in that mark or update the action to run more tests

**Comment by jamie-cunningham** [comment]
I've added the unit test mark to the mocked tests since they appear to be unit tests checking that `env.step()` returns a terminated condition when appropriate

**Review by keatincf — APPROVED** [review]
Looks good. Approved and will merge

**Pull request merged**
