### PR TITLE
33 environment step passes nonetype controls to backend

### LINKED ISSUE #33: Environment step passes NoneType controls to backend
The `step` method of gym and pettingzoo envs is able to pass NoneTypes to the sim backend `add_control` method which only accepts `list`s and `np.array`s.

### PR DESCRIPTION
**Pull request by jamie-cunningham**
Adds action space check to environment step.

### CODE REVIEW

**Comment by keatincf** [comment]
Rather than preventing NoneType, should we treat NoneType as a marker for using the default action (don't add a control to the control queue if NoneType is provided)? I'm trying to figure out if there's a way to utilize the default action.

**Comment by jamie-cunningham** [comment]
> Rather than preventing NoneType, should we treat NoneType as a marker for using the default action (don't add a control to the control queue if NoneType is provided)? I'm trying to figure out if there's a way to utilize the default action.

I was originally going that route but I couldn't think of a clean way to document it. Open to suggestions though since I agree that's a totally valid route.

**Comment by keatincf** [comment]
> > Rather than preventing NoneType, should we treat NoneType as a marker for using the default action (don't add a control to the control queue if NoneType is provided)? I'm trying to figure out if there's a way to utilize the default action.
> 
> I was originally going that route but I couldn't think of a clean way to document it. Open to suggestions though since I agree that's a totally valid route.

We can probably do something similar to what is done with the `SafeRLSimulator` where we expect agents to be providing valid actions to manipulate the entity within the simulation.  I don't think an agent would know about the default action of an entity within the simulation.  It might come up with its own default action.  For a single agent environment, there should never be a case where no action is provided for an entity.

For a multi-agent environment, actively controlled entities will have a valid action while done entities will not be provided an action (note that doesn't mean None) and will end up using a default action

**Comment by jamie-cunningham** [comment]
> > > Rather than preventing NoneType, should we treat NoneType as a marker for using the default action (don't add a control to the control queue if NoneType is provided)? I'm trying to figure out if there's a way to utilize the default action.
> > 
> > 
> > I was originally going that route but I couldn't think of a clean way to document it. Open to suggestions though since I agree that's a totally valid route.
> 
> We can probably do something similar to what is done with the `SafeRLSimulator` where we expect agents to be providing valid actions to manipulate the entity within the simulation. I don't think an agent would know about the default action of an entity within the simulation. It might come up with its own default action. For a single agent environment, there should never be a case where no action is provided for an entity.
> 
> For a multi-agent environment, actively controlled entities will have a valid action while done entities will not be provided an action (note that doesn't mean None) and will end up using a default action

In that case should we just expect the policy (however its presented) to submit a valid action OR None? And if None where should we document the environment's behavior (default action supplied by the backend in our case)?

I could be misunderstanding your reply so apologies if that's the case.

**Comment by keatincf** [comment]
> > > > Rather than preventing NoneType, should we treat NoneType as a marker for using the default action (don't add a control to the control queue if NoneType is provided)? I'm trying to figure out if there's a way to utilize the default action.
> > > 
> > > 
> > > I was originally going that route but I couldn't think of a clean way to document it. Open to suggestions though since I agree that's a totally valid route.
> > 
> > 
> > We can probably do something similar to what is done with the `SafeRLSimulator` where we expect agents to be providing valid actions to manipulate the entity within the simulation. I don't think an agent would know about the default action of an entity within the simulation. It might come up with its own default action. For a single agent environment, there should never be a case where no action is provided for an entity.
> > For a multi-agent environment, actively controlled entities will have a valid action while done entities will not be provided an action (note that doesn't mean None) and will end up using a default action
> 
> In that case should we just expect the policy (however its presented) to submit a valid action OR None? And if None where should we document the environment's behavior (default action supplied by the backend in our case)?
> 
> I could be misunderstanding your reply so apologies if that's the case.

I guess that depends on whether policies can actually select None as an action or if there's always some value.

In the multi-agent environment, I'm thinking you'd receive a dictionary where the keys can be a subset of the entities in the environment.  Entities in the action map are provided a valid action.  Entities not in the action map are essentially given a None, but not explicitly and would end up getting a default action.  So, I wasn't thinking a policy would provide a None, but just some value within the action space.

**Comment by jamie-cunningham** [comment]
> > > > > Rather than preventing NoneType, should we treat NoneType as a marker for using the default action (don't add a control to the control queue if NoneType is provided)? I'm trying to figure out if there's a way to utilize the default action.
> > > > 
> > > > 
> > > > I was originally going that route but I couldn't think of a clean way to document it. Open to suggestions though since I agree that's a totally valid route.
> > > 
> > > 
> > > We can probably do something similar to what is done with the `SafeRLSimulator` where we expect agents to be providing valid actions to manipulate the entity within the simulation. I don't think an agent would know about the default action of an entity within the simulation. It might come up with its own default action. For a single agent environment, there should never be a case where no action is provided for an entity.
> > > For a multi-agent environment, actively controlled entities will have a valid action while done entities will not be provided an action (note that doesn't mean None) and will end up using a default action
> > 
> > 
> > In that case should we just expect the policy (however its presented) to submit a valid action OR None? And if None where should we document the environment's behavior (default action supplied by the backend in our case)?
> > I could be misunderstanding your reply so apologies if that's the case.
> 
> I guess that depends on whether policies can actually select None as an action or if there's always some value.
> 
> In the multi-agent environment, I'm thinking you'd receive a dictionary where the keys can be a subset of the entities in the environment. Entities in the action map are provided a valid action. Entities not in the action map are essentially given a None, but not explicitly and would end up getting a default action. So, I wasn't thinking a policy would provide a None, but just some value within the action space.

Ah gotcha. The current implementation of the safe-autonomy-simulation backend actually does this by default. If no action is provided and the entity is still present in the simulation then the default action will be applied. So if we receive an action map that only contains a subset of the possible agents then any agents not listed just wouldn't provide an action (aka control) during the gymnasium/pettingzoo step which will trigger a default action in the simulator.

**Comment by keatincf** [comment]
I think we've resolved the discussion, so I'll go ahead an approve the PR

**Review by keatincf — APPROVED** [review]
Resolved conversation and the current implementation matches up with what we discussed.  Approved and good to merge

**Comment by jamie-cunningham** [comment]
Great, thank you so much for running through this!

**Pull request merged**
